//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormOverlapDetection.MergedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class kom
    {
        public kom()
        {
            this.PRIZ = new HashSet<PRIZ>();
        }
    
        public int ID { get; set; }
        public int id_from_base { get; set; }
        public int source_db_id { get; set; }
        public string N_KOM { get; set; }
        public string V_VS { get; set; }
        public string N_E { get; set; }
        public string ST { get; set; }
        public string V_CH { get; set; }
        public string REZH_KOM { get; set; }
        public Nullable<System.DateTime> D_OTPR { get; set; }
        public string V_SHET { get; set; }
        public Nullable<int> VSEGO { get; set; }
        public Nullable<int> VA { get; set; }
        public Nullable<int> MTLB { get; set; }
        public Nullable<int> SUD { get; set; }
        public string Z_PREDS { get; set; }
        public string PREDS { get; set; }
        public string S_UD { get; set; }
        public string N_UD { get; set; }
        public string VIDAN { get; set; }
        public Nullable<System.DateTime> D_VID { get; set; }
        public string PRIM { get; set; }
        public string SPEC { get; set; }
        public string VUS1 { get; set; }
        public string VUS2 { get; set; }
        public string VUS3 { get; set; }
        public Nullable<int> PR { get; set; }
        public Nullable<System.DateTime> D_PR { get; set; }
        public string RAILROAD { get; set; }
        public string V_OKRUG { get; set; }
        public Nullable<int> FL_UB { get; set; }
        public Nullable<int> FL_PEREOD { get; set; }
        public Nullable<int> NARAD { get; set; }
        public string GOROD { get; set; }
        public string STREET { get; set; }
        public string PHONE { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> ISSIBVO { get; set; }
        public string DOLJNOST { get; set; }
        public Nullable<short> FOLLOW_OFICER { get; set; }
        public Nullable<short> FOLLOW_PRAPOR { get; set; }
        public Nullable<short> FOLLOW_SOLDERS { get; set; }
        public string NVESHAT { get; set; }
        public Nullable<System.DateTime> DVESHAT { get; set; }
        public Nullable<short> KOLSUHPAY { get; set; }
        public short SYST { get; set; }
        public string POEZD { get; set; }
        public string VID_TR { get; set; }
        public string t_otpr { get; set; }
        public string N_DOV { get; set; }
        public Nullable<System.DateTime> D_DOV { get; set; }
        public int FL_DISPLAY { get; set; }
        public Nullable<int> DOPUSK { get; set; }
    
        public virtual sourceDatabase sourceDatabase { get; set; }
        public virtual ICollection<PRIZ> PRIZ { get; set; }
    }
}
