//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormOverlapDetection.MergedModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MergedModelEntities : DbContext
    {
        public MergedModelEntities()
            : base("name=MergedModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kom> kom { get; set; }
        public virtual DbSet<PRIZ> PRIZ { get; set; }
        public virtual DbSet<sourceDatabase> sourceDatabase { get; set; }
    }
}
