//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormOverlapDetection.MergedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sourceDatabase
    {
        public sourceDatabase()
        {
            this.kom = new HashSet<kom>();
            this.PRIZ = new HashSet<PRIZ>();
        }
    
        public int ID { get; set; }
        public string dbName { get; set; }
    
        public virtual ICollection<kom> kom { get; set; }
        public virtual ICollection<PRIZ> PRIZ { get; set; }
    }
}
